spring.application.name=journalApp

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=journaldb

#if authenticate using username and password
#spring.data.mongodb.username=enter username
#spring.data.mongodb.password=enter password
